### ISSUE TITLE
Please investigate this termination

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#124]
The initialization file is attached.
[test.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1688849/test.grmpy.txt)

> raceback (most recent call last):
>   File "./run.py", line 35, in <module>
>     grmpy.estimate('test.grmpy.ini')
>   File "/home/peisenha/ownCloud/office/workspace/software/repositories/organizations/grmToolbox/grmpy/grmpy/estimate/estimate.py", line 46, in estimate
>     x0 = start_values(dict_, data, option)
>   File "/home/peisenha/ownCloud/office/workspace/software/repositories/organizations/grmToolbox/grmpy/grmpy/estimate/estimate_auxiliary.py", line 89, in start_values
>     probitRslt = sm.Probit(data_frame.D, XZ).fit(disp=0)
>   File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py", line 1600, in fit
>     disp=disp, callback=callback, **kwargs)
>   File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py", line 204, in fit
>     disp=disp, callback=callback, **kwargs)
>   File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/statsmodels/base/model.py", line 458, in fit
>     Hinv = np.linalg.inv(-retvals['Hessian']) / nobs
>   File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 513, in inv
>     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
>   File "/home/peisenha/.envs/grmToolbox/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
>     raise LinAlgError("Singular matrix")
> numpy.linalg.linalg.LinAlgError: Singular matrix
>

**Comment by peisenha** [comment]
The problem is that the last covariate  in the outcome equations is binary and takes a value of one in all realizations since the simulated probability of this is 0.9973 as seen in the initialization file. So, please add this as a test to our check.py. Note that this is special in the sense that we now need to set up explicit tests for the dataset that is supposed to provide the basis for the estimation.

**Comment by SeBecker** [comment]
This is done.
