### ISSUE TITLE
Plot for Reliabiltiy Section

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#125]
Please add a version of the plot for Local Instrumental Variables as in http://nbviewer.jupyter.org/github/policyMetrics/course/blob/master/lectures/material/06_monte_carlo_exploration/lecture.ipynb to the reliability section.

**Comment by benediktkauf** [comment]
I have made some progress on this issue already, however when I try to run the code in my branch, I get the following error: 


  File "C:\Users\master\Anaconda4\lib\site-packages\grmpy\test\random_init.py", line 169, in print_dict
    for i, _ in enumerate(dict_[label]['coeff']):

 KeyError: 'coeff'


This doesn't make any sense as the line mentioned in the error is something completely different in my branch. Sebastian and I have had similar problems before and Sebastian mentioned that it might have something to do with the PyPI package "grmpy" not being updated but he didn't know a feasible solution either. Do you know what to do with this problem?

**Comment by benediktkauf** [comment]
I have added 'fig-local-instrumental-variable.py' to docs/figures. If you encounter any errors after the one mentioned above is fixed, just comment here and I will take care of them.

**Comment by peisenha** [comment]
@benediktkauf, @SeBecker  will reach out to you tomorrow and discuss installation in editable mode 

$ pip install -e .

This ensures you are always importing the local version of the files and not the package that is uploaded to pypi.

**Comment by SeBecker** [comment]
Small instruction:
1. Move to the directory where you cloned the grmpy repository
2. Use `pip install -e grmpy` or skip step one and use `pip install -e path/to/grmpy/repo`
3. enjoy ;)

Nevertheless, I think this issues and #95 are equivalent. Maybe it would be a good idea to merge them.

**Comment by peisenha** [comment]
This is not yet properly done. The graphs seem to be not part of the online repo, but are referenced in the documentation.

**Comment by SeBecker** [comment]
This is done, see: [doc](http://grmpy.readthedocs.io/en/sebecker/reliability.html)
