### ISSUE TITLE
Fix docstring

### ISSUE THREAD

**Issue by SeBecker** [OpenSourceEconomics/grmpy#131]
As you can see from the [Travis test](https://travis-ci.org/grmToolbox/grmpy/jobs/355805066) outcomes there seems to be a problem regarding the import from test/auxiliary.py. I think the solution for this is quite simple. You just have to align the docstring of the refactor_results function. I would ask you do it in your branch to avoid any merge conflicts (because i don't know if your local branch is some commits ahead).

**Comment by benediktkauf** [comment]
Done. Sorry for the inconvenience.
