### ISSUE TITLE
Review of documentation

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#138]
Please find below some remarks about the current state of the documentation in develop

- repeatedly we point to the old repository grmToolbox/grmpy, please comb through the package and fix everywhere. See installation.html as a example, or the badges in the software engineering section
- some references are not properly formatted 
- the figures in the reliability section are not part of the repo at this point
- please make sure that the online documentation for develop actually compiles properly on readthedocs.org
- please remove all reference about the ability to simulate binary covariates from the documentation. I just want to be able to use this in teaching at a later stage.

**Comment by peisenha** [comment]
@benediktkauf , please confirm all done, then close.

**Comment by benediktkauf** [comment]
all done
