### ISSUE TITLE
Order Column

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#143]
What is the colum **Order** in some of the tables in http://grmpy.readthedocs.io/en/develop/tutorial.html?

**Comment by SeBecker** [comment]
The order column contains the covariate labeling. At the moment you have to specify an integers for each coeffcient in the Treated, Untreated and Cost section. For instance if you assign the same value for  one coefficient in the treated and one in the cost section, the program will recognize that the specified covariate impacts the treatment output and the associated costs. The specified covariate will not affect the untreated output as long as there is no coefficient in the untreated section that has the same order value. In a nutshell the order column allows to specify covariates that only affect one pre-specified section or combinations of sections. Just let me know if you doesn't want this feature to be integrated in the tutorial section.

**Comment by peisenha** [comment]
Thank you for the clarification. Please call it column instead and state somewhere in the tutorial that the integer in the column number refers to the column in the relevant dataset.

**Comment by peisenha** [comment]
@benediktkauf , gentle reminder
