### ISSUE TITLE
sphinxcontrib.bibtex

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#155]
Please add sphinxcontrib.bibtex to environment file, otherwise doc cannot be build

**Comment by peisenha** [comment]
This is not done properly, please test before committing ...

**Comment by bekauf** [comment]
Are we talking about the readthedocs doc? I tested it before commiting and it worked just fine. The only problem I see is that readthedocs doesn't update the "latest" version to the "develop" version.

**Comment by SeBecker** [comment]
The module is included in the env file see [here](https://github.com/OpenSourceEconomics/grmpy/blob/develop/environment.yml)
