### ISSUE TITLE
not all requirements to run promotional notebook in requirements and environment file

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#157]
Please add , for example  

> ~/external_storage/ownCloud/office/workspace/OpenSourceEconomics/grmpy/promotion/04_grmpy_tutorial_notebook/auxiliary.py in <module>()
>       9 import json
>      10 
> ---> 11 from linearmodels.iv import IV2SLS
>      12 from grmpy.simulate.simulate_auxiliary import simulate_unobservables
>      13 from grmpy.estimate.estimate_output import calculate_mte
> 
> ModuleNotFoundError: No module named 'linearmodels'
>

**Comment by SeBecker** [comment]
I added linearmodels to the req file. I will include it in the upcoming environment file as well.

**Comment by peisenha** [comment]
@bekauf , please finish this and then close ...

**Comment by SeBecker** [comment]
linearmodels is included in the current version of the environment.yml file.
