### ISSUE TITLE
failed build of doc

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#161]
Running Sphinx v1.7.9
making output directory...
loading pickled environment... not yet created

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2

@bekauf please add to environment file

**Comment by bekauf** [comment]
Added

**Comment by peisenha** [comment]
@bekauf , please always check if working. If you have questions getting it to run, please reach out ...

**Comment by bekauf** [comment]
This works now, right?

**Comment by SeBecker** [comment]
sphinx_rtd_theme is included in the environment.yml file. I tested the setup, so this is done.
