### ISSUE TITLE
Reliability Test

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#95]
Please set up and document the outcome of a reliability test here http://grmpy.readthedocs.io/en/latest/reliability.html

**Comment by peisenha** [comment]
Please add something along the lines of the notebook from the lecture and http://respy.readthedocs.io/en/latest/reliability.html

**Comment by SeBecker** [comment]
As mentioned in #125, I planned to merge both issues, so here is the current description/plan.

I will upload a script that replicates the figures from Philipps Monte Carlo lecture. I would appreciate If @benediktkauf could integrate the script in the waf process. Afterwards we will tackle the documentation.

**Comment by peisenha** [comment]
This is done.
